import React from "react";
import type {Metadata} from "next";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer/Footer";
import QueryProvider from "@/providers/QueryProvider";
import {ReactQueryDevtools} from "@tanstack/react-query-devtools";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";
import {routing} from "@/i18n/routing";
import "@/styles/main.scss";
import Toastify from "@/components/common/toastify/Toastify";


export const metadata: Metadata = {
  title: "Full E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params: {locale},}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as "en" | "ar")) {
    return notFound();
  }


  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages({locale});

  return (
    <html lang={locale}>
    <body>
    <Navbar/>
    <QueryProvider>
      <NextIntlClientProvider messages={messages}>
        <ReactQueryDevtools initialIsOpen={false}/>
        <main>{children}</main>
        <Toastify/>
      </NextIntlClientProvider>
    </QueryProvider>
    <Footer/>

    </body>
    </html>
  );
}
